# linode-us — Linode VPS (45.33.39.244, Linode Newark)
#
# Hand-maintained (generated by nixos-infect, grub patched to "nodev").
# The disk is a single partitionless ext4 on /dev/sda; Linode's hypervisor
# boots by reading /boot/grub/grub.cfg (the guest MBR is never executed),
# hence "nodev" — see docs/install-nixos-on-linode.md.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.loader.grub.device = "nodev";

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "xen_blkfront"
    "vmw_pvscsi"
  ];
  boot.initrd.kernelModules = [ "nvme" ];

  fileSystems."/" = {
    device = "/dev/sda";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/sdb"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}